### PR TITLE
Adds additional options support for wkhtmltopdf recipe

### PR DESCRIPTION
**Pull request by charlieknoll**
Options:

dpi (default 96)
javascript-delay (default 200)
print-media-type
window-status
disable-smart-shrinking

### CODE REVIEW

**Comment by bjrmatos** [comment]
great job! 🎉  welcome to our contributors list 😄 and thnks!

**Comment by bjrmatos** [comment]
we are going to include these changes in our incoming release (probably tomorrow)

**Comment by bjrmatos** [comment]
docs are updated with the new options too -> https://jsreport.net/learn/wkhtmltopdf

**Comment by bjrmatos** [comment]
@charlieknoll your changes landed in `v1.3.0` 🎉 🎉

**Comment by charlieknoll** [comment]
Thanks for updating the docs, I missed that

**Pull request merged**
